version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --timeout-keep-alive 120
    container_name: cctv_backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cctv_db
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - cctv-network

  db:
    image: postgres:15
    container_name: cctv_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cctv_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cctv-network

  frontend:
    build: ./frontend
    container_name: cctv_frontend
    networks:
      - cctv-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cctv_nginx
    ports:
      - "80:80" # Map HTTP port 80 ของ host → container
      - "443:443" # Map HTTPS port 443 ของ host → container
    depends_on:
      - backend
      - frontend
    networks:
      - cctv-network

networks:
  cctv-network:
    driver: bridge

volumes:
  postgres_data:
